#Requires -Version 5
<#
.SYNOPSIS
    Release helper for a single KeePass-plugin repo (KPPasskeyChecker / KP2FAChecker).

.DESCRIPTION
    A three-stage, branch + PR release flow. CHANGELOG.md is generated by Prepare from the
    branch commits; the GitHub release TYPE is explicit: draft | prerelease | release.

    Workflow:
      1. Create the release branch from main:
             git switch -c release/vX.Y.Z
      2. Develop on the branch -- one commit per completed feature. Whenever a change is
         visible to a plugin user, add its release note under "## [Unreleased]" in
         CHANGELOG.md as part of that same change: release notes address users, commit
         subjects address developers, and only the author of the change knows which of the
         two a given edit deserves.
      3. release.ps1 -Version X.Y.Z -Stage Preview
         Promotes [Unreleased] to "## [X.Y.Z]" (uncommitted) and shows the version-bump
         plan. Review / edit the section now -- this is the approval gate for the release
         notes.
      4. release.ps1 -Version X.Y.Z -Stage Prepare
         Bumps the three version files, commits everything (working-tree changes + bump,
         including the reviewed CHANGELOG), pushes the branch and opens a PR against main.
         No build -- Publish always rebuilds from main.
      5. Merge the PR on GitHub.
      6. release.ps1 -Version X.Y.Z -Stage Publish
         Checks out main, pulls, builds, creates the GitHub release.

    Stages:
      Preview  (default)   Show the branch commits and the version-bump plan, and prepare the
                           CHANGELOG section for -Version (uncommitted) so it can be reviewed
                           and edited before Prepare commits it: [Unreleased] is promoted to
                           "## [x.y.z]", or -- only when it holds no entries -- the section is
                           derived from commit subjects as a fallback. Preview also prints
                           commit count against entry count, so a user-visible change that
                           never got an entry is visible at the gate. Commits, pushes and
                           releases nothing; an existing section for that version is never
                           overwritten (re-running Preview is safe).
      Prepare              Generate/update CHANGELOG.md, bump version files, commit,
                           push branch, open PR.
                           RESUMABLE: if the version is already bumped and the branch
                           already pushed, only ensures the PR exists.
      Publish              Run AFTER the PR is merged: checkout main, pull, build, create
                           the GitHub release vX.Y.Z with .plgx + .dll assets.

    gh must be authenticated with a token that has (fine-grained) Contents: write,
    Pull requests: write and Administration: read/write on the repo (or classic 'repo').
    A missing 'Pull requests' permission fails Prepare at gh pr create with
    "Resource not accessible by personal access token (createPullRequest)".
    Prepare is resumable: re-run it and it skips to opening the PR.

.PARAMETER Version
    Target semantic version, e.g. 0.3.0 (no leading 'v'). Required for Prepare and Publish.
    For Preview, defaults to the current version in VersionInfo.txt.

.PARAMETER Type
    GitHub release type: draft | prerelease | release. Default: prerelease.

.PARAMETER Stage
    Preview (default) | Prepare | Publish.

.PARAMETER Force
    Skip the interactive confirmation prompts in Prepare / Publish.

.EXAMPLE
    .\release.ps1 -Version 0.3.0 -Type prerelease
    .\release.ps1 -Version 0.3.0 -Type prerelease -Stage Prepare
    # ...merge the PR on GitHub...
    .\release.ps1 -Version 0.3.0 -Type prerelease -Stage Publish
#>
[CmdletBinding()]
param(
    [string]$Version,
    [ValidateSet('draft', 'prerelease', 'release')] [string]$Type = 'prerelease',
    [ValidateSet('Preview', 'Prepare', 'Publish')]   [string]$Stage = 'Preview',
    [switch]$Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$RepoRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $RepoRoot

# ---- helpers ----------------------------------------------------------------

function Resolve-Gh {
    $c = Get-Command gh -ErrorAction SilentlyContinue
    if ($c) { return $c.Source }
    $fallback = Join-Path $env:ProgramFiles 'GitHub CLI\gh.exe'
    if (Test-Path $fallback) { return $fallback }
    throw "GitHub CLI (gh) not found. Install it (winget install GitHub.cli) or add it to PATH."
}

function Get-PluginInfo {
    $vi = Join-Path $RepoRoot 'VersionInfo.txt'
    if (-not (Test-Path $vi)) { throw "VersionInfo.txt not found in $RepoRoot." }
    foreach ($line in (Get-Content $vi)) {
        if ($line -match '^(?<name>[^:\s][^:]*):(?<ver>\d+\.\d+\.\d+)\s*$') {
            return [pscustomobject]@{ Name = $Matches.name; Version = $Matches.ver }
        }
    }
    throw "Could not parse a 'Name:Version' line from VersionInfo.txt."
}

function Get-BranchCommits {
    # Commit subjects on current branch not reachable from main, as '- subject' bullet lines.
    $lines = git log main..HEAD --pretty=format:"- %s" --no-merges 2>&1
    if ($LASTEXITCODE -ne 0 -or -not $lines) { return @() }
    return @($lines)
}

function Get-ChangelogSection([string]$ver) {
    $path = Join-Path $RepoRoot 'CHANGELOG.md'
    if (-not (Test-Path $path)) { throw "CHANGELOG.md not found. Run -Stage Prepare first." }
    $lines = Get-Content $path
    $start = -1
    for ($i = 0; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -match ('^##\s*\[' + [regex]::Escape($ver) + '\]')) { $start = $i; break }
    }
    if ($start -lt 0) { throw "CHANGELOG.md has no '## [$ver]' section. Run -Stage Prepare first." }
    $body = New-Object System.Collections.Generic.List[string]
    for ($i = $start + 1; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -match '^##\s*\[') { break }
        $body.Add($lines[$i])
    }
    $text = ($body -join "`n").Trim()
    if ([string]::IsNullOrWhiteSpace($text)) { throw "The '## [$ver]' section in CHANGELOG.md is empty." }
    return $text
}

function Set-ChangelogSection([string]$ver, [string]$sectionText) {
    # Inserts or replaces the ## [ver] section in CHANGELOG.md, preserving the rest.
    $path = Join-Path $RepoRoot 'CHANGELOG.md'
    if (-not (Test-Path $path)) {
        [System.IO.File]::WriteAllText($path, "# Changelog`n`n", (New-Object System.Text.UTF8Encoding($false)))
    }
    $lines = Get-Content $path
    $pattern = '^##\s*\[' + [regex]::Escape($ver) + '\]'
    $sectionLines = $sectionText -split "`n"

    $start = -1
    for ($i = 0; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -match $pattern) { $start = $i; break }
    }

    $out = New-Object System.Collections.Generic.List[string]
    if ($start -ge 0) {
        # Replace existing section for this version.
        for ($i = 0; $i -lt $start; $i++) { $out.Add($lines[$i]) }
        foreach ($l in $sectionLines) { $out.Add($l) }
        $out.Add("")
        $next = $start + 1
        while ($next -lt $lines.Count -and $lines[$next] -notmatch '^##\s*\[') { $next++ }
        for ($i = $next; $i -lt $lines.Count; $i++) { $out.Add($lines[$i]) }
    } else {
        # Insert before the first existing ## [...] section (after the file header/intro).
        $insertAt = $lines.Count
        for ($i = 0; $i -lt $lines.Count; $i++) {
            if ($lines[$i] -match '^##\s*\[') { $insertAt = $i; break }
        }
        for ($i = 0; $i -lt $insertAt; $i++) { $out.Add($lines[$i]) }
        foreach ($l in $sectionLines) { $out.Add($l) }
        $out.Add("")
        for ($i = $insertAt; $i -lt $lines.Count; $i++) { $out.Add($lines[$i]) }
    }
    [System.IO.File]::WriteAllText($path, ($out -join "`n"), (New-Object System.Text.UTF8Encoding($false)))
}

function Convert-UnreleasedToVersion([string]$ver) {
    # Promotes the "## [Unreleased]" section to "## [ver] - <today>" and leaves a fresh, empty
    # [Unreleased] heading behind for the next version. Returns the number of entries moved, or 0
    # when there is nothing to promote (no such section, or it holds no "- " entries).
    #
    # This is the primary way release notes come to exist. Entries are written by whoever makes
    # the change, in user-facing wording, at the moment it is clear whether a user would notice
    # the change at all -- a judgement that cannot be recovered afterwards from commit subjects,
    # because those address developers while release notes address users.
    $path = Join-Path $RepoRoot 'CHANGELOG.md'
    if (-not (Test-Path $path)) { return 0 }
    $lines = @(Get-Content $path)

    $start = -1
    for ($i = 0; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -match '^##\s*\[Unreleased\]') { $start = $i; break }
    }
    if ($start -lt 0) { return 0 }

    $end = $start + 1
    while ($end -lt $lines.Count -and $lines[$end] -notmatch '^##\s*\[') { $end++ }

    $body = @()
    for ($i = $start + 1; $i -lt $end; $i++) { $body += $lines[$i] }
    $entryCount = @($body | Where-Object { $_ -match '^\s*-\s+\S' }).Count
    if ($entryCount -eq 0) { return 0 }

    while ($body.Count -gt 0 -and [string]::IsNullOrWhiteSpace($body[0])) {
        $body = @($body | Select-Object -Skip 1)
    }
    while ($body.Count -gt 0 -and [string]::IsNullOrWhiteSpace($body[$body.Count - 1])) {
        $body = @($body | Select-Object -First ($body.Count - 1))
    }

    $today = Get-Date -Format 'yyyy-MM-dd'
    $out = New-Object System.Collections.Generic.List[string]
    for ($i = 0; $i -lt $start; $i++) { $out.Add($lines[$i]) }
    $out.Add('## [Unreleased]')
    $out.Add('')
    $out.Add("## [$ver] - $today")
    $out.Add('')
    foreach ($l in $body) { $out.Add($l) }
    $out.Add('')
    for ($i = $end; $i -lt $lines.Count; $i++) { $out.Add($lines[$i]) }

    [System.IO.File]::WriteAllText($path, ($out -join "`n"), (New-Object System.Text.UTF8Encoding($false)))
    return $entryCount
}

function Get-VersionFiles {
    param([string]$pluginName)
    @(
        (Join-Path $RepoRoot 'VersionInfo.txt'),
        (Join-Path $RepoRoot ("src\{0}\Properties\AssemblyInfo.cs" -f $pluginName)),
        (Join-Path $RepoRoot ("src\{0}\PluginVersion.cs" -f $pluginName))
    )
}

function Update-VersionFiles {
    param([string]$pluginName, [string]$oldVer, [string]$newVer)
    if ($oldVer -eq $newVer) { Write-Host "  Version already $newVer -- no file changes needed." -ForegroundColor DarkGray; return }
    foreach ($f in (Get-VersionFiles $pluginName)) {
        if (-not (Test-Path $f)) { throw "Expected version file not found: $f" }
        $raw = Get-Content $f -Raw
        # The 3-part version is a prefix of the 4-part AssemblyVersion (X.Y.Z.0), so replacing
        # the 3-part string updates VersionInfo, both Assembly*Version attributes and the doc
        # comment in one pass.
        $new = $raw.Replace($oldVer, $newVer)
        if ($new -ne $raw) {
            [System.IO.File]::WriteAllText($f, $new, (New-Object System.Text.UTF8Encoding($false)))
            Write-Host ("  bumped {0}" -f (Resolve-Path $f -Relative))
        }
    }
}

function Invoke-Build {
    $build = Join-Path $RepoRoot 'build.ps1'
    if (-not (Test-Path $build)) { throw "build.ps1 not found in $RepoRoot." }
    Write-Host "==> Building" -ForegroundColor Cyan
    & $build
    if ($LASTEXITCODE -ne 0) { throw "build.ps1 failed (exit $LASTEXITCODE)." }
}

function Invoke-CoverageGate {
    # Per-class coverage gate (release-only; the pre-commit hook stays a plain 'dotnet test'
    # for fast feedback -- this is the authoritative gate before Prepare/Publish). Thresholds
    # are calibrated below the measured per-class floor with margin (see coverage.runsettings /
    # TestCoverageExemptions.Entries for the documented exemptions this report already reflects).
    param([string]$StageName)

    Write-Host "==> Running coverage gate (per-class line/branch thresholds)" -ForegroundColor Cyan
    $resultsDir = Join-Path $RepoRoot 'TestResults'
    if (Test-Path $resultsDir) { Remove-Item $resultsDir -Recurse -Force }

    & dotnet test (Join-Path $RepoRoot 'KPPasskeyChecker.sln') --configuration Release --nologo `
        --settings (Join-Path $RepoRoot 'coverage.runsettings') `
        --collect:"XPlat Code Coverage" `
        --results-directory $resultsDir
    if ($LASTEXITCODE -ne 0) { throw "Coverage collection run failed. Fix the code and re-run $StageName." }

    $report = Get-ChildItem -Path $resultsDir -Filter 'coverage.cobertura.xml' -Recurse |
        Sort-Object LastWriteTime -Descending | Select-Object -First 1
    if (-not $report) { throw "No coverage.cobertura.xml produced under $resultsDir." }

    $gateScript = Join-Path $RepoRoot 'tools\coverage-gate.ps1'
    if (-not (Test-Path $gateScript)) { throw "coverage-gate.ps1 not found at $gateScript." }

    & $gateScript -ReportPath $report.FullName -LineThreshold 55 -BranchThreshold 60
    if ($LASTEXITCODE -ne 0) { throw "Coverage gate failed. Raise coverage on the reported class(es) and re-run $StageName." }
    Write-Host "  Coverage gate passed." -ForegroundColor Green
    Write-Host ""
}

function Get-Assets {
    param([string]$pluginName)
    $buildDir = Join-Path $RepoRoot 'build'
    $plgx = Join-Path $buildDir ("{0}.plgx" -f $pluginName)
    $dll  = Join-Path $buildDir ("{0}.dll"  -f $pluginName)
    foreach ($a in @($plgx, $dll)) { if (-not (Test-Path $a)) { throw "Build artifact missing: $a" } }
    # Use forward slashes: gh treats backslashes as escape characters and mis-parses the path.
    return @("build/{0}.plgx" -f $pluginName, "build/{0}.dll" -f $pluginName)
}

function Confirm-Or-Exit([string]$prompt) {
    if ($Force) { return }
    $ans = Read-Host "$prompt (y/N)"
    if ($ans -notmatch '^(y|yes)$') { Write-Host "Aborted." -ForegroundColor Yellow; exit 2 }
}

function Format-ChangelogSection([string]$ver, [string[]]$rawCommits) {
    # Categorise commit subjects into Keep-a-Changelog sections.
    # Recognised prefixes (conventional commits): feat/add -> Added; fix/bugfix -> Fixed;
    # security/sec -> Security; chore/build/refactor/docs/style/perf/test -> Changed.
    # Unrecognised prefix -> Added. Prefix + colon is stripped from the displayed text.
    $added = @(); $changed = @(); $fixed = @(); $security = @()
    foreach ($raw in $rawCommits) {
        $subject = ($raw -replace '^-\s*', '').Trim()
        if     ($subject -match '^(feat(ure)?|add)[:\s]+(.+)$')             { $added    += '- ' + $Matches[3].Trim() }
        elseif ($subject -match '^(fix|bugfix)[:\s]+(.+)$')                 { $fixed    += '- ' + $Matches[2].Trim() }
        elseif ($subject -match '^(sec(urity)?)[:\s]+(.+)$')                { $security += '- ' + $Matches[3].Trim() }
        elseif ($subject -match '^(chore|build|refactor|docs?|style|perf|test)[:\s]+(.+)$') { $changed += '- ' + $Matches[2].Trim() }
        else                                                                 { $added    += '- ' + $subject }
    }
    $today = Get-Date -Format 'yyyy-MM-dd'
    $lines = @("## [$ver] - $today", '')
    if ($added.Count    -gt 0) { $lines += '### Added';    $lines += $added;    $lines += '' }
    if ($changed.Count  -gt 0) { $lines += '### Changed';  $lines += $changed;  $lines += '' }
    if ($fixed.Count    -gt 0) { $lines += '### Fixed';    $lines += $fixed;    $lines += '' }
    if ($security.Count -gt 0) { $lines += '### Security'; $lines += $security; $lines += '' }
    while ($lines.Count -gt 0 -and $lines[-1] -eq '') { $lines = $lines[0..($lines.Count - 2)] }
    return $lines -join "`n"
}

function Get-TypeArgs([string]$t) {
    switch ($t) {
        'draft'      { return @('--draft') }
        'prerelease' { return @('--prerelease') }
        'release'    { return @() }
    }
}

function Invoke-EnsurePr([string]$gh, [string]$branch, [string]$ver, [string]$notes) {
    Write-Host "==> Ensuring a PR exists" -ForegroundColor Cyan
    $listJson = (& $gh pr list --head $branch --base main --state open --json url) -join "`n"
    if ($LASTEXITCODE -ne 0) { throw "gh pr list failed (exit $LASTEXITCODE)." }
    if ($listJson -match '\{') {
        Write-Host ("  A PR for '{0}' is already open." -f $branch) -ForegroundColor Green
    } else {
        & $gh pr create --base main --head $branch --title ("Release {0}" -f $ver) --body $notes
        if ($LASTEXITCODE -ne 0) {
            throw ("gh pr create failed (exit $LASTEXITCODE). " +
                "'Resource not accessible by personal access token (createPullRequest)' means the token " +
                "lacks 'Pull requests: Read and write' -- add it to the fine-grained PAT, then re-run " +
                "Prepare (it skips to opening the PR automatically).")
        }
    }
}

# ---- main -------------------------------------------------------------------

$info    = Get-PluginInfo
$plugin  = $info.Name
$current = $info.Version
$versionSpecified = -not [string]::IsNullOrWhiteSpace($Version)
if (-not $versionSpecified) { $Version = $current }
if ($Version -notmatch '^\d+\.\d+\.\d+$') { throw "-Version must be x.y.z (got '$Version')." }

$tag    = "v$Version"
$branch = "release/$tag"

Write-Host ""
Write-Host ("=== {0} release | plugin={1} | {2} -> {3} | type={4} | stage={5} ===" -f $tag, $plugin, $current, $Version, $Type, $Stage) -ForegroundColor Cyan
Write-Host ""

switch ($Stage) {

    'Preview' {
        $commits = Get-BranchCommits
        Write-Host "Branch commits (will become CHANGELOG entries):" -ForegroundColor White
        if ($commits.Count -eq 0) {
            Write-Host "  (no commits on this branch yet)" -ForegroundColor DarkGray
        } else {
            $commits | ForEach-Object { Write-Host "  $_" }
        }

        # Write the proposed CHANGELOG section now (uncommitted) so it can be reviewed and edited
        # BEFORE Prepare commits it -- Preview is the approval gate. An existing section is never
        # overwritten, so re-running Preview is safe and manual edits survive. Requires an explicit
        # -Version: without it $Version is just the current (already released) version.
        $draftWritten = $false
        if ($versionSpecified) {
            $changelogPath = Join-Path $RepoRoot 'CHANGELOG.md'
            $changelogHasSection = (Test-Path $changelogPath) -and
                ((Get-Content $changelogPath) -match ('^##\s*\[' + [regex]::Escape($Version) + '\]'))

            Write-Host ""
            Write-Host "CHANGELOG:" -ForegroundColor White
            if ($changelogHasSection) {
                Write-Host ("  ## [{0}] already exists -- left untouched. Edit it if needed:" -f $Version) -ForegroundColor DarkGray
                Write-Host ("  {0}" -f $changelogPath)
            } else {
                $draftWritten = $true
                $promoted = Convert-UnreleasedToVersion $Version
                if ($promoted -gt 0) {
                    Write-Host ("  Promoted [Unreleased] -> ## [{0}] ({1} entries), fresh [Unreleased] left behind." -f $Version, $promoted) -ForegroundColor Yellow
                } else {
                    $draftCommits = $commits
                    if ($draftCommits.Count -eq 0) { $draftCommits = @("- (no feature commits found on branch)") }
                    Set-ChangelogSection $Version (Format-ChangelogSection $Version $draftCommits)
                    Write-Host ("  [Unreleased] held no entries -- FELL BACK to deriving ## [{0}] from {1} commit subject(s)." -f $Version, $commits.Count) -ForegroundColor Yellow
                    Write-Host "  The fallback yields developer wording, not release notes. Entries belong under" -ForegroundColor DarkGray
                    Write-Host "  [Unreleased], written while the change is made, by whoever knows if a user notices." -ForegroundColor DarkGray
                }

                $sectionText = Get-ChangelogSection $Version
                $entryCount = @(($sectionText -split "`n") | Where-Object { $_ -match '^\s*-\s+\S' }).Count
                Write-Host ("  Branch commits: {0}   |   release-note entries: {1}" -f $commits.Count, $entryCount)
                if ($commits.Count -gt $entryCount) {
                    Write-Host "  A gap is expected -- most commits are invisible to users. Still worth a glance:" -ForegroundColor DarkGray
                    Write-Host "  a missing entry for a user-visible change fails silently, unlike a wrong one." -ForegroundColor DarkGray
                }
                Write-Host ("  Review / edit it now: {0}" -f $changelogPath) -ForegroundColor Yellow
                Write-Host "  Discard with: git checkout -- CHANGELOG.md" -ForegroundColor DarkGray
                Write-Host ""
                ($sectionText -split "`n") | ForEach-Object { Write-Host "  | $_" }
            }
        }

        Write-Host ""
        Write-Host "Version bump:" -ForegroundColor White
        if ($current -eq $Version) {
            Write-Host "  (already at $Version)" -ForegroundColor DarkGray
        } else {
            Get-VersionFiles $plugin | ForEach-Object {
                Write-Host ("  {0}: {1} -> {2}" -f (Resolve-Path $_ -Relative), $current, $Version)
            }
        }

        Write-Host ""
        Write-Host "Uncommitted working-tree changes:" -ForegroundColor White
        $st = git status --short
        if ([string]::IsNullOrWhiteSpace(($st -join ''))) {
            Write-Host "  (clean)" -ForegroundColor DarkGray
        } else {
            $st | ForEach-Object { Write-Host "  $_" }
        }

        Write-Host ""
        Write-Host "Plan (Prepare):" -ForegroundColor White
        Write-Host "  1. Use the CHANGELOG.md ## [$Version] section (prepared here in Preview; Prepare only generates it if still missing)"
        Write-Host "  2. Bump version files ($current -> $Version)"
        Write-Host "  3. git add -A && git commit -m 'Release $Version'"
        Write-Host "  4. git push -u origin $branch"
        Write-Host "  5. Open PR: $branch -> main"
        Write-Host ""
        Write-Host "Plan (Publish, after PR merge):" -ForegroundColor White
        Write-Host ("  Build from main, create GitHub release {0} ({1}) with .plgx + .dll" -f $tag, $Type)
        Write-Host ""
        if ($draftWritten) {
            Write-Host "Nothing committed, pushed or released. Review / edit the CHANGELOG draft, then re-run with -Stage Prepare." -ForegroundColor Green
        } else {
            Write-Host "Nothing changed. Re-run with -Stage Prepare when development is complete." -ForegroundColor Green
        }
    }

    'Prepare' {
        $gh = Resolve-Gh
        git rev-parse --is-inside-work-tree > $null 2>&1
        if ($LASTEXITCODE -ne 0) { throw "Not a git repository." }

        $currentBranch = git rev-parse --abbrev-ref HEAD
        if ($currentBranch -ne $branch) {
            throw ("Expected to be on branch '{0}' but currently on '{1}'.`nSwitch to the release branch first: git switch {0}" -f $branch, $currentBranch)
        }

        # Self-check: run before any changes; abort immediately on failure.
        Write-Host "==> Running self-check" -ForegroundColor Cyan
        & "$RepoRoot\tools\run-selfcheck.ps1"
        if ($LASTEXITCODE -ne 0) {
            throw "Self-check failed. Fix the code and re-run Prepare."
        }
        Write-Host "  Self-check passed." -ForegroundColor Green
        Write-Host ""

        # xUnit tests: mandatory gate.
        Write-Host "==> Running dotnet test (xUnit gate)" -ForegroundColor Cyan
        & dotnet test (Join-Path $RepoRoot 'KPPasskeyChecker.sln') --configuration Release --nologo
        if ($LASTEXITCODE -ne 0) { throw "xUnit tests failed. Fix the code and re-run Prepare." }
        Write-Host "  xUnit tests passed." -ForegroundColor Green
        Write-Host ""

        # Per-class coverage gate: mandatory (release-only; pre-commit stays a plain 'dotnet test').
        Invoke-CoverageGate 'Prepare'

        # Resumability checks: skip steps already completed.
        $alreadyBumped = ($current -eq $Version)
        $remoteOutput  = (git ls-remote --heads origin $branch 2>&1) -join ''
        $alreadyPushed = (-not [string]::IsNullOrWhiteSpace($remoteOutput))

        if ($alreadyBumped -and $alreadyPushed) {
            Write-Host "Version already bumped and branch already pushed -- skipping to PR." -ForegroundColor Yellow
        } else {
            # Generate CHANGELOG section from branch commits — only if no section for this
            # version exists yet (allows manually writing the CHANGELOG before Prepare).
            $changelogPath = Join-Path $RepoRoot 'CHANGELOG.md'
            $changelogHasSection = (Test-Path $changelogPath) -and
                ((Get-Content $changelogPath) -match ('^##\s*\[' + [regex]::Escape($Version) + '\]'))
            if ($changelogHasSection) {
                $sectionText = Get-ChangelogSection $Version
                $hasSubsections = $sectionText -match '###\s+(Added|Changed|Fixed|Security|Removed|Deprecated)'
                if ($hasSubsections) {
                    Write-Host "==> CHANGELOG.md ## [$Version] is already in Keep a Changelog format." -ForegroundColor DarkGray
                } else {
                    Write-Host "==> CHANGELOG.md ## [$Version] exists but lacks subsections -- reformatting." -ForegroundColor Yellow
                    $rawLines = ($sectionText -split "`n") | Where-Object { $_ -match '^\s*-\s+' }
                    if (-not $rawLines) { $rawLines = @("- (no entries found)") }
                    $sectionText = Format-ChangelogSection $Version @($rawLines)
                    Set-ChangelogSection $Version $sectionText
                    Write-Host "  Reformatted. Review / edit the file if needed:" -ForegroundColor Yellow
                    Write-Host ("  {0}" -f $changelogPath)
                }
                Write-Host ""
                ($sectionText -split "`n") | ForEach-Object { Write-Host "  | $_" }
                Write-Host ""
            } else {
                Write-Host "==> Generating CHANGELOG section from branch commits" -ForegroundColor Cyan
                $commits = Get-BranchCommits
                if ($commits.Count -eq 0) { $commits = @("- (no feature commits found on branch)") }
                $sectionText = Format-ChangelogSection $Version $commits
                Set-ChangelogSection $Version $sectionText

                Write-Host ""
                Write-Host "  CHANGELOG.md written. Review / edit the file now if needed:" -ForegroundColor Yellow
                Write-Host ("  {0}" -f $changelogPath)
                Write-Host ""
                ($sectionText -split "`n") | ForEach-Object { Write-Host "  | $_" }
                Write-Host ""
            }

            Confirm-Or-Exit "Proceed with version bump, commit, push and PR?"

            if (-not $alreadyBumped) {
                Write-Host "==> Bumping version files" -ForegroundColor Cyan
                Update-VersionFiles $plugin $current $Version
            }

            Write-Host "==> Committing and pushing" -ForegroundColor Cyan
            git add -A
            if ($LASTEXITCODE -ne 0) { throw "git add failed." }
            git commit -m ("Release {0}" -f $Version)
            if ($LASTEXITCODE -ne 0) { throw "git commit failed." }
            git push -u origin $branch
            if ($LASTEXITCODE -ne 0) { throw "git push failed." }
        }

        $notes = Get-ChangelogSection $Version
        Invoke-EnsurePr $gh $branch $Version $notes

        Write-Host ""
        Write-Host ("Branch + PR ready for {0}. Merge the PR on GitHub, then run:" -f $tag) -ForegroundColor Green
        Write-Host ("  .\release.ps1 -Version {0} -Type {1} -Stage Publish" -f $Version, $Type) -ForegroundColor Green
    }

    'Publish' {
        $gh = Resolve-Gh
        Write-Host "==> Switching to main and pulling" -ForegroundColor Cyan
        git checkout main
        if ($LASTEXITCODE -ne 0) { throw "git checkout main failed." }
        git pull --ff-only
        if ($LASTEXITCODE -ne 0) { throw "git pull --ff-only failed." }
        $onMain = (Get-PluginInfo).Version
        if ($onMain -ne $Version) {
            throw ("main is at version {0}, expected {1}. Is the release PR merged?" -f $onMain, $Version)
        }

        $notes = Get-ChangelogSection $Version
        Confirm-Or-Exit ("Create GitHub release {0} ({1}) from main with built assets?" -f $tag, $Type)

        # Self-check: run before any changes; abort immediately on failure.
        Write-Host "==> Running self-check" -ForegroundColor Cyan
        & "$RepoRoot\tools\run-selfcheck.ps1"
        if ($LASTEXITCODE -ne 0) {
            throw "Self-check failed. Fix the code and re-run Publish."
        }
        Write-Host "  Self-check passed." -ForegroundColor Green
        Write-Host ""

        # xUnit tests: mandatory gate before build.
        Write-Host "==> Running dotnet test (xUnit gate)" -ForegroundColor Cyan
        & dotnet test (Join-Path $RepoRoot 'KPPasskeyChecker.sln') --configuration Release --nologo
        if ($LASTEXITCODE -ne 0) { throw "xUnit tests failed. Fix the code and re-run Publish." }
        Write-Host "  xUnit tests passed." -ForegroundColor Green
        Write-Host ""

        # Per-class coverage gate: mandatory (release-only; pre-commit stays a plain 'dotnet test').
        Invoke-CoverageGate 'Publish'

        Invoke-Build
        $assets    = Get-Assets $plugin
        $typeArgs  = Get-TypeArgs $Type

        # Notes go via a temp file: mixing splatted arrays with a multi-line --notes string trips
        # PowerShell 5.1 native-arg quoting ('-' bullets become asset globs -> "no matches found").
        # build\ is gitignored so this file is never committed.
        $notesFile = Join-Path $RepoRoot 'build\_relnotes.md'
        Set-Content $notesFile $notes -Encoding utf8

        Write-Host ("==> Creating GitHub release {0} ({1})" -f $tag, $Type) -ForegroundColor Cyan
        & $gh release create $tag @assets --target main --title ("{0} {1}" -f $plugin, $Version) --notes-file $notesFile @typeArgs
        if ($LASTEXITCODE -ne 0) { throw "gh release create failed (exit $LASTEXITCODE)." }

        Write-Host ""
        Write-Host ("Done. Release {0} created as '{1}'." -f $tag, $Type) -ForegroundColor Green
    }
}
